#!/bin/dash

repo=".shrug"

if ! test -d ".shrug/"; then
    >&2 echo "shrug-add: error: no .shrug directory containing shrug repository exists"
    exit
fi

if test $# -eq 0; then
    >&2 echo "usage: shrug-add <filenames>"
    exit
fi

for var in "$@"
do
    if test -f "$var"; then
        branch=`cat ".shrug/branch.txt" | head -1`
        cp "$var" ".shrug/.$branch/.index/"
    else
        branch=`cat ".shrug/branch.txt" | head -1`
        if test -f "$repo/.$branch/$var"; then
            echo "$var - deleted" > ".shrug/.$branch/.log/bin.txt" && rm "$repo/.$branch/$var"
        else
            >&2 echo "shrug-add: error: can not open '$var'"
            exit
        fi
    fi
done
