#!/bin/dash

########################################################################
############################## SHRUG_SHOW ##############################
########################################################################

## This file adds files provided, into the repo of the current branch.
## The logic is:
## -> if a .shrug subdir exists, then;
##      -> the overall logic is quite simple. Handle errors accordingly, and otherwise
##         if we find the filename and the number, with the dash syntax we've
##         gone for as described in shrug-commit, then simply cat that file.
##      -> one important quality - if we can't find a file with the version in our current
##         branch, we should search the logs of other branches using find and 
##         if it's there, cat that.
## -> handle errors otherwise.

if ! test -d ".shrug"; then
    >&2 echo "shrug-show: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

if test $# -eq 0 || test $# -gt 1; then
    >&2 echo "usage: shrug-show <commit>:<filename>"
    exit 1
fi

if test $# -eq 1; then
    check=`echo "$1" | egrep ':' | wc -l`
    if test $check -eq 0; then
        >&2 echo "shrug-show: error: invalid object $1"
        exit 1
    fi
fi

branch=`cat ".shrug/branch.txt" | head -1`
logfiles=".shrug/.$branch/.log"
indexfiles=".shrug/.$branch/.index"
filename=`echo $1 | sed 's/:/ /' | cut -d' ' -f2`
commit_number=`echo $1 | sed 's/:/ /' | cut -d' ' -f1`

if test "$commit_number" = "" && test -f "$indexfiles/$filename";
then
    cat "$indexfiles/$filename"
elif test -f "$logfiles/$commit_number-$filename";
then
    cat "$logfiles/$commit_number-$filename"
else
    if ! test "$commit_number" = ""; then
        ## So firstly, check that the commit number given isn't impossible.
        total_commits=`cat ".shrug/branch.txt" | tail -1`
        test $total_commits -ne 0 && total_commits=$(($total_commits - 1))
        if test $total_commits -lt $commit_number; then
            >&2 echo "shrug-show: error: unknown commit '$commit_number'"
            exit 1
        else
            ## Then, if the file isn't existent, we can check our whole .shrug subdirectory to see
            ## if it's in the *log* of any other branch.
            other_branch=`find .shrug/.*/.log -name "$commit_number-$filename" | wc -l`
            if test $other_branch -gt 0; then
                file=`find .shrug/.*/.log -name "$commit_number-$filename"`
                cat "$file"
            else
                >&2 echo "shrug-show: error: '$filename' not found in commit $commit_number"
                exit 1
            fi
        fi
    else
        ## So over here we just check if the file in itself exists in the index.
        if ! test -f "$indexfiles/$filename"; then
            >&2 echo "shrug-show: error: '$filename' not found in index"
            exit 1
        else
            cat "$indexfiles/$filename"
        fi
    fi
fi

