#!/bin/dash

if test $# -gt 0; then
    >&2 echo "usage: shrug-init"
    exit
fi

if test -d ".shrug"; then
    >&2 echo "shrug-init: error: .shrug already exists"
else
    mkdir ".shrug"
    mkdir ".shrug/.master"
    mkdir ".shrug/.master/.index"
    mkdir ".shrug/.master/.log"
    mkdir ".shrug/.master/.merged/"
    touch ".shrug/branch.txt"
    echo "master" > ".shrug/branch.txt"
    echo 0 >> ".shrug/branch.txt"
    touch ".shrug/.master/.log/log.txt"
    touch ".shrug/.master/.log/bin.txt"
    touch ".shrug/.master/.log/status.txt"
    echo "Initialized empty shrug repository in .shrug"
fi
