#!/bin/dash

if ! test -d ".shrug"; then
    >&2 echo "shrug-log: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

commits=`cat ".shrug/branch.txt" | tail -1`

if test $commits -eq 0; then
    >&2 echo "shrug-log: error: your repository does not have any commits yet"
    exit 1
fi

if test $# -gt 0; then
    >&2 echo "usage: shrug-log"
    exit 1
fi

branch=`cat ".shrug/branch.txt" | head -1`
cat ".shrug/.$branch/.log/log.txt" | sort -r | egrep -v "^$" | uniq

