#!/bin/dash

if ! test -d ".shrug"; then
    >&2 echo "shrug-checkout: error: no .shrug directory containing shrug repository exists"
    exit 1
fi 

if test $# -eq 1 && test "$1" = "-d"; then
    >&2 echo "shrug-checkout: error: branch name required"
    exit 1
fi

branch=`cat ".shrug/branch.txt" | head -1`
commits=`cat ".shrug/branch.txt" | tail -1`

if test $commits -eq 0; then
    >&2 echo "shrug-checkout: error: your repository does not have any commits yet"
    exit 1
fi

if test $# -gt 1; then
    >&2 echo "usage: shrug-checkout <branch>"
    exit 1
fi

if test "$1" = "$branch"; then
    echo "Already on '$branch'"
elif ! test -d ".shrug/.$1"; then
    >&2 echo "shrug-checkout: error: unknown branch '$1'"
    exit 1
else
    existing_files=`ls | tr ' ' '\n' | egrep -v "shrug-*" | egrep -v "diary.txt" | egrep -v "test*" | egrep -v "merge*"`
    for f in $existing_files
    do
        cp "$f" ".shrug/.$branch/.files"
        if test -d ".shrug/.$1/.files" && test -f ".shrug/.$1/.files/$f"; then
            # copy over index for that file
            test -f ".shrug/.$branch/.index/$f" && cp ".shrug/.$branch/.index/$f" ".shrug/.$1/.index/$f"
            if test -f ".shrug/.$branch/$f"; then
                # copy over file if it has unstaged changes, uncommitted changes.
                dir_and_index=`diff ".shrug/.$branch/.index/$f" "$f" | wc -l`
                index_and_repo=`diff ".shrug/.$branch/$f" ".shrug/.$branch/.index" | wc -l`
                dir_and_repo=`diff ".shrug/.$branch/$f" "$f" | wc -l`
                test $dir_and_index -gt 0 && cp "$f" ".shrug/.$1/.files"
                test $index_and_repo -eq 0 && test $dir_and_repo -gt 0 && cp "$f" ".shrug/.$1/.files"
                test $index_and_repo -eq 0 && test $dir_and_repo -eq 0 && test $dir_and_index -eq 0 && cp ".shrug/.$1/$f" ".shrug/.$1/.files" && cp ".shrug/.$1/$f" ".shrug/.$1/.index"
            elif test -f ".shrug/.$branch/.files/$f"; then
                # copy over file if it is untracked.
                error="false"
                errorfiles=""
                if test -f ".shrug/.$branch/.files/$f" && ! test -f ".shrug/.$branch/$f" && ! test -f ".shrug/.$branch/.index/$f"; then
                    if test -f ".shrug/.$1/.files/$f"; then
                        difference=`diff ".shrug/.$1/.files/$f" ".shrug/.$branch/.files/$f" | wc -l`
                        test $difference -gt 0 && error="true"
                        errorfiles="$errorfiles$f "
                    fi
                    test "$error" = "true" && 
                    >&2 echo "shrug-checkout: error: Your changes to the following files would be overwritten by checkout:" &&
                    for nomerge in $errorfiles
                    do
                        echo "$nomerge"
                    done && exit 1
                    test "$error" = "false" && cp "$f" ".shrug/.$1/.files"
                fi
            fi
        else
            # over here, this means that the file we are checking does not exist in the branch we are changing to, but it does
            # in the current one. so, if untracked, let's add it to the branch we are changing to.

            # what we need to do though, is check if there is a difference between this version, and the version in the branch
            # we are going to - if any at all.
            # test "$branch" = "brancha" && echo "hi, checking file $f"
            error="false"
            errorfiles=""
            if test -f ".shrug/.$branch/.files/$f" && ! test -f ".shrug/.$branch/$f" && ! test -f ".shrug/.$branch/.index/$f"; then
                if test -f ".shrug/.$1/.files/$f"; then
                    difference=`diff ".shrug/.$1/.files/$f" ".shrug/.$branch/.files/$f" | wc -l`
                    test $difference -gt 0 && error="true"
                    errorfiles="$errorfiles$f "
                fi
                test "$error" = "true" && # echo "the error files are as follows: '$errorfiles'" &&
                >&2 echo "shrug-checkout: error: Your changes to the following files would be overwritten by checkout:" &&
                for nomerge in $errorfiles
                do
                    echo "$nomerge"
                done && exit 1
                test "$error" = "false" && cp "$f" ".shrug/.$1/.files"
            fi
        fi
    done
    if test -d ".shrug/.$1/.files"; then
        files=`ls ".shrug/.$1/.files" | tr ' ' '\n' | egrep -v "shrug-*" | egrep -v "diary.txt"`
        empty=`printf "$files\n" | tr '\n' ' ' | wc -l`
        for existing_file in $existing_files
        do
            filename=`basename "$existing_file"`
            if ! test -f ".shrug/.$1/.files/$filename"; then
                rm "$existing_file"
            fi
        done
        for branch_file in $files
        do
            filename=`basename "$branch_file"`
            cp ".shrug/.$1/.files/$branch_file" "."
        done
    fi
    sed -i '1s/.*/'$1/ ".shrug/branch.txt"
    echo "Switched to branch '$1'"
fi