#!/bin/dash

########################################################################
############################## SHRUG_RM ################################
########################################################################

## This file provides a way to remove files from the repo to different extents.
## The logic is:
## -> if a .shrug subdir exists, and files have been provided, then;
##      -> if force is provided, don't even think twice - just remove the necessary files.
##      -> if force cache is provided, don't even think twice - just remove the necessary index files.
##      -> if just cache is provided, handle errors as needed and output the "file - unstaged" line.
##         if index file is deleted, just so that we can track it as a change and a commit. This is
##         referenced in the shrug-commit comments.
##      -> if just a file is given, we need to ensure that it doesn't have any conflicting changes.
##         these conditions are shown at bottom. If all good, we then remove it from the index and 
##         currdir, and then we output "file - deleted" into our bin.txt, for use in shrug-status
##         and also our commit tracking.
## -> otherwise, handle the errors.

if ! test -d ".shrug"; then
    >&2 echo "shrug-rm: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

branch=`cat ".shrug/branch.txt" | head -1`
index=".shrug/.$branch/.index"
log=".shrug/.$branch/.log/log.txt"
force=0
cached=0
commits=`cat ".shrug/branch.txt" | tail -1`

if test $commits -eq 0; then
    >&2 echo "shrug-rm: error: your repository does not have any commits yet"
    exit 1
fi

if test $# -eq 0; then
    >&2 echo "usage: shrug-rm [--force] [--cached] <filenames>"
    exit 1
fi

if test "$1" = "--force"; then
    force=1
elif test "$1" = "--cached"; then
    cached=1
fi

files=`echo $@ | sed 's/--cached//' | sed 's/--force//'`

for f in $files
do
    if ! test -f "$index/$f"; then
        >&2 echo "shrug-rm: error: '$f' is not in the shrug repository"
        exit 1
    fi
done

if test $force -eq 1; then
    for f in $files
    do
        if ! test -f ".shrug/.$branch/.index/$f"; then
            >&2 echo "shrug-rm: error: '$f' is not in the shrug repository"
            exit 1
        else
            if test "$2" = "--cached"; then
                rm ".shrug/.$branch/.index/$f"
            else
                rm ".shrug/.$branch/.index/$f"
                rm $f
            fi
        fi
    done
else
    for file in $files
    do
        if ! test -f ".shrug/.$branch/$file"; then
            if ! test -f "$index/$file"; then
                >&2 echo "shrug-rm: error: '$file' is not in the shrug repository"
                exit 1
            else
                if ! test $cached -eq 1; then
                    >&2 echo "shrug-rm: error: '$file' has changes staged in the index"
                    exit 1
                fi
                test $cached -eq 1 && rm "$index/$file" && echo "$file - unstaged" >> ".shrug/.$branch/.log/bin.txt"
            fi
        else
            compare_repo_dir=`diff ".shrug/.$branch/$file" "$file" | wc -l`
            compare_repo_index=`diff "$index/$filename" ".shrug/.$branch/$file" | wc -l`
            compare_index_dir=`diff "$index/$filename" "$file" | wc -l`

            if test $compare_repo_index -gt 0 && test $compare_index_dir -gt 0; then
                >&2 echo "shrug-rm: error: '$file' in index is different to both working file and repository"
                exit 1
            elif test $cached -eq 1; then
                rm "$index/$file"
                echo "$file - unstaged" >> ".shrug/.$branch/.log/bin.txt"
            elif test $compare_repo_dir -eq 0; then
                ## we require to check that the file is in fact in the index here, because sometimes they can be unstaged
                ## and then called to be removed again without cache.
                test -f "$index/$file" && rm "$index/$file"
                rm "$file"
                echo "$file - deleted" >> ".shrug/.$branch/.log/bin.txt"
            else
                test $compare_repo_index -eq 0 &&
                test $compare_index_dir -gt 0 &&
                >&2 echo "shrug-rm: error: '$file' in repository is different to working file" &&
                exit 1

                test $compare_repo_index -gt 0 &&
                test $compare_index_dir -eq 0 &&
                >&2 echo "shrug-rm: error: '$file' has changes staged in the index" &&
                exit 1
            fi
        fi
    done
fi